-- CRIANDO TABELAS --

CREATE TABLE Cliente(
CPF VARCHAR(15),
Nome VARCHAR(20),
DataNasc DATE,
Telefone VARCHAR(20),
Endereco VARCHAR(50),
Email VARCHAR(50),
CONSTRAINT CPF_CLI_PK PRIMARY KEY(CPF)
);

CREATE TABLE Funcionario(
CPF VARCHAR(15),
Nome VARCHAR(20),
Endereco VARCHAR(50), 
DataNasc DATE,
Telefone VARCHAR(20),
Email VARCHAR(50),
Login VARCHAR(50),
Senha VARCHAR(50),
CONSTRAINT CPF_FUNC_PK PRIMARY KEY(CPF)
);

CREATE TABLE Veiculos(
Placa VARCHAR(20),
Marca VARCHAR(20), 
Modelo VARCHAR(20),
Ano INT,
Disponivel BOOLEAN,
Cor VARCHAR(20),
ValorHora FLOAT,
CONSTRAINT VEI_PK PRIMARY KEY(Placa)
);

CREATE TABLE Locacoes(
Id INT,
DataInicio DATE,
DataFim DATE,
VeiculoPlaca VARCHAR(20), 
ClienteCPF VARCHAR(15),
FuncionarioCPF VARCHAR(15),
CONSTRAINT LOC_PK PRIMARY KEY(ID),
CONSTRAINT LOC_VEI_FK FOREIGN KEY(VeiculoPlaca) REFERENCES Veiculos(Placa),
CONSTRAINT LOC_FUN_FK FOREIGN KEY(FuncionarioCPF) REFERENCES Funcionario(CPF),
CONSTRAINT LOC_CLI_FK FOREIGN KEY(ClienteCPF) REFERENCES Cliente(CPF)
);

--- SELECTS DAS TABELAS ---

SELECT * FROM Cliente;
SELECT * FROM Funcionario;
SELECT * FROM Locacoes;
SELECT * FROM Veiculos;

-- APAGANDO TABELAS --

DROP TABLE Locacoes;
DROP TABLE Veiculos;
DROP TABLE Funcionario;
DROP TABLE Cliente;


