CREATE TABLE Cliente(
	ID_CLIENTE INT AUTO_INCREMENT,
	NOME_CLIENTE VARCHAR(100),
	EMAIL VARCHAR(100),
	TELEFONE VARCHAR(15),
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID_CLIENTE)
)

CREATE TABLE Produto(
	ID_PRODUTO INT AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(100),
	DESCRICAO TEXT,
	PRECO DECIMAL(10,2),
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO)
)

CREATE TABLE Pedidos(
	ID_PEDIDO INT AUTO_INCREMENT,
	ID_CLIENTE INT,
	DATA_PEDIDO DATE,
	STATUS VARCHAR(50),
	CONSTRAINT PK_PEDIDOS PRIMARY KEY(ID_PEDIDO),
	CONSTRAINT FK_PCLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES Cliente(ID_CLIENTE)
)

CREATE TABLE Itens_pedidos(
	ID_ITENS_PEDIDOS INT AUTO_INCREMENT,
	ID_PEDIDO INT,
	ID_PRODUTO INT,	
	CONSTRAINT PK_ITENS_PEDIDOS PRIMARY KEY(ID_ITENS_PEDIDOS),
	CONSTRAINT FK_ITPEDIDO FOREIGN KEY(ID_PEDIDO) REFERENCES Pedidos(ID_PEDIDO),
	CONSTRAINT FK_ITPRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES Produto(ID_PRODUTO)
)